name: Test Connection to Servers

on:
  workflow_dispatch:

jobs:
  update-security-group:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Debug Directory Structure
        run: ls -la scripts
        
      - name: Install Dependencies
        run: pip install -r scripts/requirements.txt
        
      - name: Get Public IP of Runner
        id: get-ip
        run: echo "RUNNER_IP=$(curl -s https://api.ipify.org)">> $GITHUB_ENV

      - name: Authorize Runner IP in Security Group
        run: |
          python scripts/authorize_ip.py ${{env.RUNNER_IP}}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          SECURITY_GROUP_ID: ${{secrets.SECURITY_GROUP_ID}}

      - name: Fetch Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -R 51.20.85.188 || true # remove existing entry if any
          ssh-keyscan -H 51.20.85.188 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY_EC2: ${{secrets.SSH_PRIVATE_KEY_EC2}}

      - name: Set Up SSH Key
        run: |
            echo "$SSH_PRIVATE_KEY_EC2" >> ssh_key.pem
            chmod 400 ssh_key.pem
            echo "private key retreived"

      - name: Debug Key Content
        run: cat ssh_key.pem

      - name: Test SSH Conncetion
        run: |
            echo "Testing SSH connection..."
            ssh -i ssh_key.pem -o HostKeyAlgorithms=+ssh-rsa ec2-user@51.20.85.188 
            echo "SSH Connection Successful"
          
  # test-ssh:
  #   needs: update-security-group
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set Up SSH Key
  #       env:
  #         SSH_PRIVATE_KEY_EC2: ${{secrets.SSH_PRIVATE_KEY_EC2}}
  #       run: |
  #           echo "SSH_PRIVATE_KEY_EC2" > /tmp/ssh_key.pem
  #           chmod 600 /tmp/ssh_key.pem
          
  
  #     - name: Test SSH Connection
  #       run: |
  #         echo "Testing SSH connection..."
  #         ssh -i /tmp/ssh_key.pem -o StrictHostKeyChecking=no ec2-user@51.20.85.188 echo "SSH Connection Successful"
